name: Backend CI/CD

on:
  push:
    branches: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ecom_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        options: --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.0

      - name: Install dependencies
        run: go mod tidy

      - name: Generate .env.test
        run: echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env.test

      - name: Run Tests
        run: APP_ENV=test go test ./...

      - name: Build Docker Image
        run: docker build -f Dockerfile.prod -t commerce-api-app .

      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag commerce-api-app ${{ secrets.DOCKER_USERNAME }}/commerce-api-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/commerce-api-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH & Deploy Docker Container on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker system prune -f || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/commerce-api-app:latest
            sudo docker stop ecommerce-api || true
            sudo docker rm ecommerce-api || true
            sudo docker run -d \
              --name ecommerce-api \
              --env-file /home/ubuntu/.env \
              -e APP_ENV=production \
              -p 80:8080  \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/commerce-api-app:latest
